version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Comfac@1234
      POSTGRES_DB: facman
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:Comfac@1234@db:5432/facman

volumes:
  db_data: 